# --- Generated by scripts/bootstrap.sh into cluster.auto.tfvars.json --------
# The "unused" defaults keep destroy runs working when the tfvars file is
# gone (fresh clone, cleaned artifacts); applies always follow bootstrap.sh,
# which writes the real values.
variable "infra_id" {
  type        = string
  default     = "unused"
  description = "Installer infrastructure ID from install-dir/metadata.json (e.g. tfe-ocp-x7k2m). Prefixes every resource name and the kubernetes.io/cluster tag."
}

variable "rhcos_ami" {
  type        = string
  default     = "unused"
  description = "RHCOS AMI for this region/version, resolved by bootstrap.sh from openshift-install coreos print-stream-json."
}

variable "ignition_ca" {
  type        = string
  default     = "unused"
  description = "Ignition CA certificate (data URL) extracted from master.ign — lets nodes trust the Machine Config Server at api-int:22623."
}

variable "cluster_name" {
  type        = string
  default     = "unused"
  description = "OpenShift cluster name (e.g. tfe-ocp)."
}

variable "base_domain" {
  type        = string
  default     = "unused"
  description = "Public Route 53 zone the cluster lives under (api.<cluster>.<base_domain>)."
}

variable "bootstrap_ign_bucket" {
  type        = string
  default     = "unused"
  description = "S3 bucket holding bootstrap.ign (created by bootstrap.sh)."
}

# --- Operator-tunable --------------------------------------------------------
variable "bootstrap_enabled" {
  type        = bool
  default     = true
  description = "Keep the bootstrap node. Set false (and apply) after 'wait-for bootstrap-complete'."
}

variable "master_instance_type" {
  type        = string
  default     = "m6i.xlarge" # 4 vCPU / 16 GiB — control plane minimum
  description = "Instance type for the 3 control plane nodes."
}

variable "worker_instance_type" {
  type        = string
  default     = "m6i.xlarge"
  description = "Instance type for worker nodes."
}

variable "worker_count" {
  type        = number
  default     = 3
  description = "Number of worker nodes (spread across the private subnets)."
}

variable "api_ingress_cidrs" {
  type        = list(string)
  default     = ["0.0.0.0/0"]
  description = "CIDRs allowed to reach the public API (6443). Demo default is open; tighten to your IP for anything longer-lived."
}

variable "vpc_cidr" {
  type        = string
  default     = "10.10.0.0/16"
  description = "Must match networking.machineNetwork in install-config.template.yaml."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Additional tags applied to all AWS resources."
}
